on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: Build VSCode Web artifact
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build VSCode Web
        run: make vscode-web-artifact

      - name: Upload Release Artifact
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.action_ref }}
          allowUpdates: true
          artifacts: "vscode-web*.zip"